### ISSUE TITLE
zoom value數值增加時，led排數增加規則更動

### ISSUE THREAD

**Issue by david8712403** [Sway-Light/sway-light-ht32f52352#2]
原：zoom value增加時，led最左、最右同時各加亮一排

改為：
zoom value增加時，多判斷：
前一狀態亮起總排數為偶數時，最右邊加亮一排；
前一狀態亮起總排數為奇數時，最左邊家亮一排。

**Comment by harrisonwu0220** [comment]
此程式(以下稱為in_prog_zoom)目前 push 在 develop 這個 branch。
目前遇到的問題:
使用 branch master 最新的版本執行，系統能正常讀取觸控板的訊號。
使用 in_prog_zoom 執行，系統無法正常讀取觸控板的訊號。

詳細資訊待下次視訊討論時提出!

**Comment by harrisonwu0220** [comment]
fixed in commit: 255d1a58a6d1a75a49979a2d05ea20e2f828cdac
