### ISSUE TITLE
音樂模式時，touch key滑動及縮放要可以調整LED亮度及顯示範圍大小

### ISSUE THREAD

**Issue by david8712403** [Sway-Light/sway-light-ht32f52352#3]
依討論：音樂模式時，touch key滑動及縮放要可以調整LED亮度及顯示範圍大小。
縮放顯示範圍調整時，請依：頻段間隔=32/顯示頻段數量 的規則顯示

**Comment by harrisonwu0220** [comment]
in commit: f5f0b1cb3fcda0735f7dd21a43657cbb86d1bab7
